{{/*
SPDX-License-Identifier: Apache-2.0
Copyright 2026 Hygon Information Technology Co., Ltd.
*/}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hcu-device-plugin
  labels:
  {{- include "k8s-hcu-plugin-hami.labels" . | nindent 4 }}
